# Generated by Django 4.0.6 on 2025-03-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafedra',
            name='faculty',
        ),
    ]
