# Generated by Django 5.1.7 on 2025-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_student_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='Kafedra',
            new_name='Products',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guruh',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Guruh',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
