# Generated by Django 5.1.7 on 2025-03-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_users_rename_subject_categories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
